title: The Ducking Traveller
email: theduckingtraveller@gmail.com
permalink: :title/
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://theduckingtraveller.com" # the base hostname & protocol for your site, e.g. http://example.com

author-name: Amrita Savadatti

twitter_url: https://twitter.com/theducktravels
github_username:  theduckingtraveller

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-feed

video: sunset.mp4
banner-title: > 
  The Ducking Traveller
banner-desc: > # this means to ignore newlines until "baseurl:"
  In Pursuit of Nirvana

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap