banner-title: The Ducking Traveller
email: theduckingtraveller@gmail.com
banner-desc: > # this means to ignore newlines until "baseurl:"
  In Pursuit of Nirvana
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://theduckingtraveller.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: theduckingtraveller
github_username:  theduckingtraveller

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-feed
video: sunset.mp4
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
